stages:
  - test
  - release

docker:
  stage: release
  only: ['main']
  services:
    - docker:dind
  image: jdrouet/docker-with-buildx:stable
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker buildx create --use
    - docker buildx build --platform linux/arm/v7,linux/arm64/v8,linux/amd64 --push -t $CI_REGISTRY_IMAGE .
  tags:
    - docker
